### ISSUE TITLE
Plugin cleaning after bundle is built

### ISSUE THREAD

**Issue by mriede** [johnagan/clean-webpack-plugin#67] opened 2017-09-29 12:21 UTC
Hi!

I'm using this in combination with django-webpack-loader, and often times (especially if I accidentally save two times in a row) the plugin removes the bundle _after_ it was compiled. Which leaves me with a blank page. Any idea on how to fix that?

**Comment by alexreg** [comment] 2017-10-01 21:44
This is a problem for me too! I'm using it with webpack-dev-server instead, though.

**Comment by armel22** [comment] 2017-10-05 09:59
I have the same issue

**Comment by SirNeuman** [comment] 2017-11-10 17:36
Happens to me to. More often than not it works normally, but it does sometimes clean the folder afterward it's already compiled. I'm just using babel-loader.

**Comment by jimblue** [comment] 2017-11-15 12:12
This is also a huge problem when build fail because `clean-webpack-plugin` will delete old working assets and none will replace them...
Seems very important to run this plugin after build success and before assets are written.

**Comment by jackypan1989** [comment] 2017-11-21 00:49
https://github.com/jackypan1989/del-webpack-plugin

**Comment by Clay-Ferguson** [comment] 2018-01-07 19:31
I see same issue. This plugin deletes my 'dist' folder AFTER the build is done, making it a bit counterproductive. haha.

**Comment by chrisschrijver** [comment] 2018-01-29 07:50
I submitted a pull request last week which is already merged. You can now set "beforeEmit" to true in the options and it will clean the dist folder just before the files are emitted to the output dir

**Comment by ChrisRAoW** [comment] 2018-07-25 07:02
@flurdulis I would not suggest to use this option in development. Just for production environments.

**Comment by meglio** [comment] 2018-11-16 02:14
I can confirm that the [plugin](https://github.com/jackypan1989/del-webpack-plugin) referenced by @jackypan1989 's above just solved my "-w" problem.

**Comment by chrisblossom** [comment] 2019-03-04 18:13
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.

**Closed by chrisblossom** 2019-03-04 18:13 UTC
